### PR TITLE
✨ QuaKE post

### PR DESCRIPTION
**Pull request by hayesall**
- [X] Consistent example through "Rule Mining" section with clearer introduction
- [X] "Learning QI Statements" section could use notation description, currently it drops some definitions and presents the equations
- [X] Need to look up how prior AIME work has been cited. If they're published in the Springer AI Lecture Series, there may be DOI numbers minted for these.
- [X] Footnotes/sections were rearranged a few time, put footnotes in order
- [x] Ask Harsha for formatting review (so far this pulls from her previous two posts as a "template," I'd these to have a consistent *look-and-feel* across posts)
- [ ] Ask Athresh and Harsha for content review

### CODE REVIEW

**Comment by harshakokel** [comment]
I like the quick overview :)

A few notes:
1. Each statement describes how a change in one variable ~~causes~~ influences the change in another variable.
2. Increase in BMI increases the risk of high blood pressure in patients **with** family history of hypertension more than in patients without such family history.
3. Is booktitle missing in the bibtex on purpose?
4. Add Acknowledgement.

**Comment by hayesall** [comment]
Thanks for the feedback earlier @harshakokel, got those + a couple other things.

@athresh or Harsha, let me know if there's anything that could be tweaked!

**Comment by harshakokel** [comment]
Looks good to me. 👍🏽

**Review by harshakokel — APPROVED** [review]

**Review by athresh — APPROVED** [review]
Looks good to me.

**Pull request merged**
